### ISSUE TITLE
$ astro auth login error when EE not installed

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astro-cli#76]
Expected: If I try to log in but ~~haven't created a cluster yet~~ EE is not yet installed, the CLI will give me an error message indicating what to do.

Actual:

```
$ astro auth login
panic: exit status 1

goroutine 1 [running]:
github.com/astronomerio/astro-cli/docker.Exec(0xc42022bd10, 0x2, 0x2, 0xb, 0xc42022bd18)
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/docker/docker.go:24 +0xeb
github.com/astronomerio/astro-cli/auth.Login()
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/auth/auth.go:9 +0x5c
github.com/astronomerio/astro-cli/cmd.authLogin(0x19f0f20, 0x1a1fec8, 0x0, 0x0)
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/cmd/auth.go:42 +0x20
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x19f0f20, 0x1a1fec8, 0x0, 0x0, 0x19f0f20, 0x1a1fec8)
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19ef5a0, 0x1, 0x19f0260, 0xc42022bf60)
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x19ef5a0, 0xc42022bf70, 0x15240f9)
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
    /Users/taylor/go/src/github.com/astronomerio/astro-cli/main.go:10 +0x2d
```

@andscoop What are your thoughts on this?

**Comment by andscoop** [comment]
This panic has been removed and resolved by a more detailed houston error message
